DROP TABLE IF EXISTS reportes;

CREATE TABLE reportes (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          usuario_id BIGINT NOT NULL,
                          estado VARCHAR(20),
                          s3_url VARCHAR(255),
                          fecha_creacion TIMESTAMP
);